# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  flight_api: co385841356843233542384262589472
  secret_key_base: 0787b7c432bf659139f6c82eb29888e6e639c6dc2fd56c55c3502122bf6d55f80b4b0b778ef90cd31484ee1560bbd2cbe6d705f54bb6425bfa9f795b0656c506

test:
  flight_api: co385841356843233542384262589472
  secret_key_base: b05b00709c60e956d4e80556a4b7f4ab9f02598a1b8f57fc1108e485eeec42ccf82a402bbcab7db3c5316a74a1454735d41c3524f7f108ff3043c84c746dda1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  flight_api: co385841356843233542384262589472
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
